language: ruby

rvm:
 - 2.6

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - gem update --system
  - gem install bundler

jobs:
  include:
    - stage: Checking with Rubocop
      script: bundle exec rubocop
