language: ruby

rvm:
 - 2.6

services:
  - postgresql

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

jobs:
  include:
    - stage: Checking with Rubocop
      script: bundle exec rubocop
